### ISSUE TITLE
Double buffering (node4+)

### ISSUE THREAD

**Issue by Matt-Esch** [doanythingfordethklok/hammock#21]
There is an issue regarding double buffering in > node 0.10 with pipe (the data event + write events are both called).

This was discussed here:

https://github.com/doanythingfordethklok/hammock/commit/45cc549027be86fc615fa6ffa8d41c9f1ec2df47

**Comment by doanythingfordethklok** [comment]
I probably cannot get to this until Monday, but I'll take a look

**Comment by Matt-Esch** [comment]
I've patched a local copy by just removing back compat for node 0.8. It might be a good idea to do that and bump the major version. PR incoming.

**Comment by doanythingfordethklok** [comment]
I merged it and updated the readme. Will you give that readme a review before I bump and push the major version?
